### ISSUE TITLE
openwrt-xray or openwrt-xray-plugin?

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-precompiled-feeds#2]
hello
Would try xray on your openwrt-dnsmasq-extra
Could you tell me which pacakges should be added for compiling,like openwrt-dnsmasq-extra + openwrt-xray-plugin +?
thank you

**Comment by honwen** [comment]
openwrt-dnsmasq-extra + openwrt-xray

**Comment by honwen** [comment]
and https://github.com/honwen/luci-app-xray

**Comment by honwen** [comment]
vless + xtls only

**Comment by jack338c** [comment]
@honwen 
thank you very much !
Good luck

**Comment by jack338c** [comment]
I found this :
https://github.com/XTLS/Xray-core/releases/download/v1.4.2/Xray-linux-arm32-v6.zip
PKG_ARCH:=arm32_v6 needs change to PKG_ARCH:=arm32-v6
I just tested

**Comment by honwen** [comment]
Tks

**Comment by jack338c** [comment]
> vless + xtls only

sorry to bother you, do you mean I only can use "3 VLESS + TCP + XTLS",but no others?

1 VLESS + TCP + TLS
2 VLESS + TCP +TLS + WS
3 VLESS + TCP + XTLS
4 VLESS + HTTP2 + h2c

**Comment by honwen** [comment]
Yes, only 3 is implemented.

**Comment by jack338c** [comment]
got it
thank you
