### ISSUE TITLE
xray-plugin can work with openwrt-dnsmasq-extra?

### ISSUE THREAD

**Issue by jack338c** [honwen/openwrt-precompiled-feeds#3]
hello my idol,hope everything is fine to you

I wonder if xray-plugin can work with openwrt-dnsmasq-extra,if so how to configure  xray-plugin or is it has any luci web interface support?

thanks

**Comment by honwen** [comment]
https://github.com/honwen/luci-app-shadowsocks-rust

**Comment by jack338c** [comment]
@honwen 
got it 
thank you 
have a good day !
